/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javacrud.control.VilleDAOImp;
import javacrud.gestUtil.Commune;
import java.util.HashMap;
import javax.swing.JFrame;

/**
 *
 * @author j.bory
 */
public class SelectVille extends javax.swing.JDialog {

    /**
     * Creates new form SelectVille
     */
    boolean selected;
    Commune selectedVille = new Commune();
    HashMap<Integer, Commune> ville = new HashMap<>();
    VilleDAOImp dao = new VilleDAOImp();

    public SelectVille(java.awt.Frame parent, boolean modal, Integer codePostal, String numPost) {
        super(parent, modal);
        initComponents();
        Commune commune = new Commune();
        VilleDAOImp villedaoimp = new VilleDAOImp();
        HashMap<Integer, Commune> listeVille = villedaoimp.ville(codePostal);
        selectedVille.setCode_Postal(codePostal.toString());
        selectedVille.setNum_Postal(numPost);
        DefaultTableModel uiTable = (DefaultTableModel)jTableVille.getModel();
        
        int i = 0, NumL = 0;
        for(Integer idVille : listeVille.keySet()){
            
            commune = listeVille.get(idVille);
            Object[] row = new Object[2];
            row[0] = idVille;
            row[1] = commune.getNom_Commune();
            uiTable.addRow(row);
            
            
            if(idVille.toString().equals(numPost)){
                jTableVille.setRowSelectionInterval(i, i);
                this.selectedVille.setNom_Commune(row[1].toString());
            }
            i = i+1;
        }
        

    }
    public void chargeSelectVille(){
        int i  = jTableVille.getSelectedRow();
        TableModel model = jTableVille.getModel();
        this.selectedVille.setNum_Postal(model.getValueAt(i, 0).toString());
        this.selectedVille.setNom_Commune(model.getValueAt(i, 1).toString());
        
    }

    private SelectVille(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Commune getSelectedVille() {

        return selectedVille;
        
    }

    public Boolean getSelected() {
        return selected;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valider = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVille = new javax.swing.JTable();
        Abandonner = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 335));
        setMinimumSize(new java.awt.Dimension(450, 335));
        setModal(true);
        getContentPane().setLayout(null);

        Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/valid_20.png"))); // NOI18N
        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(20, 260, 100, 30);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });
        jScrollPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jScrollPane1KeyReleased(evt);
            }
        });

        jTableVille.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Selectionner une ville"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVilleMouseClicked(evt);
            }
        });
        jTableVille.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableVilleKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVille);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 380, 240);

        Abandonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/escape_20.png"))); // NOI18N
        Abandonner.setText("Abandonner");
        Abandonner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbandonnerMouseClicked(evt);
            }
        });
        Abandonner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbandonnerActionPerformed(evt);
            }
        });
        getContentPane().add(Abandonner);
        Abandonner.setBounds(240, 260, 150, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 260, 70, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbandonnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbandonnerActionPerformed
        selected  = false;
        this.dispose();
    }//GEN-LAST:event_AbandonnerActionPerformed

    private void jScrollPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1KeyReleased

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTableVilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVilleMouseClicked
       chargeSelectVille();
        
        
        
    }//GEN-LAST:event_jTableVilleMouseClicked

    private void AbandonnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbandonnerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AbandonnerMouseClicked

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        selected = true;
        this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void jTableVilleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableVilleKeyReleased
        chargeSelectVille();
    }//GEN-LAST:event_jTableVilleKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectVille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectVille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectVille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectVille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectVille dialog = new SelectVille(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abandonner;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVille;
    // End of variables declaration//GEN-END:variables
}
