/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacrud.view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.DirectoryStream.Filter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javacrud.control.ImageDAO;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;


/**
 *
 * @author j.bory
 */
public class SelectAvatar extends javax.swing.JDialog {

    /**
     * Creates new form SelectAvatar
     */
    private final int largeurIn = 420;
    private final int hauteurIn = 495;
    private final int largeurOut = 140;
    private final int hauteurOut = 165;
    private final int maxFileSize = 5000000;
    private String pseudo;
    private boolean selected; 
    
    public SelectAvatar(java.awt.Frame parent, boolean modal, String pseudo) {
        super(parent, modal);
        this.pseudo = pseudo;
        initComponents();
    }

    private SelectAvatar(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet in SelectAvatar.java"); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        avatar = new javax.swing.JLabel();
        abandonner = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        miniature = new javax.swing.JLabel();
        Choisir = new javax.swing.JButton();
        valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-max.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(avatar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 440);

        abandonner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/escape_20.png"))); // NOI18N
        abandonner.setText("Abandonner");
        abandonner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abandonnerMouseClicked(evt);
            }
        });
        abandonner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abandonnerActionPerformed(evt);
            }
        });
        getContentPane().add(abandonner);
        abandonner.setBounds(400, 460, 140, 30);

        miniature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-min.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(miniature))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(miniature)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(630, 10, 140, 170);

        Choisir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/folder-open_20.png"))); // NOI18N
        Choisir.setText("Choisir");
        Choisir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChoisirMouseClicked(evt);
            }
        });
        Choisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoisirActionPerformed(evt);
            }
        });
        getContentPane().add(Choisir);
        Choisir.setBounds(30, 460, 140, 30);

        valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/valid_20.png"))); // NOI18N
        valider.setText("Valider");
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(220, 460, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abandonnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abandonnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abandonnerActionPerformed

    private void ChoisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoisirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChoisirActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validerActionPerformed

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        // TODO add your handling code here:
        ImageDAO.setUtImage(pseudo, (ImageIcon) this.miniature.getIcon());
        this.selected = true;
        this.dispose();
    }//GEN-LAST:event_validerMouseClicked

    private void ChoisirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChoisirMouseClicked
        // TODO add your handling code here:
        ImageIcon photo = null;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "png", "jpg", "jpeg", "gif");
        imageChooser.setCurrentDirectory(FileSystemView.getFileSystemView().getHomeDirectory());
        imageChooser.setFileFilter(filter);
        int returnValue = imageChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedImg = imageChooser.getSelectedFile();
            if (selectedImg.length() < maxFileSize) {
                try {
                    photo = ImageDAO.importImage(selectedImg.getPath(), largeurIn, hauteurIn);
                } catch (IOException ex) {
                    Logger.getLogger(SelectAvatar.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (photo != null) {
                    this.avatar.setIcon(photo);
                    try {
                        photo = ImageDAO.importImage(selectedImg.getPath(), largeurOut, hauteurOut);
                    } catch (IOException ex) {
                        Logger.getLogger(SelectAvatar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.miniature.setIcon(photo);
                } else {
                    this.avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie.jpg")));
                }
            }
        }
    }//GEN-LAST:event_ChoisirMouseClicked

    private void abandonnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abandonnerMouseClicked
        // TODO add your handling code here:
        this.selected = false;
        this.dispose();
    }//GEN-LAST:event_abandonnerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectAvatar dialog = new SelectAvatar(new javax.swing.JFrame(), true, "Etudiant");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choisir;
    private javax.swing.JButton abandonner;
    private javax.swing.JLabel avatar;
    private javax.swing.JFileChooser imageChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel miniature;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
